# Generated by Django 2.2 on 2018-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180522_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null='image', upload_to=''),
            preserve_default='image',
        ),
    ]
