# Generated by Django 2.2 on 2018-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, upload_to='image'),
            preserve_default=False,
        ),
    ]
